[package]
edition = "2021"
name = "token-factory"
version = "0.24.0"

[features]
default = []
no_api = []

[dependencies]
candid = "=0.7.14" # Because there is a build issue with ic_types::principal::PrincipalError
ic-cdk = "0.5"
ic-cdk-macros = "0.5"
ic-canister = { git = "https://github.com/infinity-swap/canister-sdk", package = "ic-canister", branch = "awkure/upgrade-fixes" }
ic-helpers = { git = "https://github.com/infinity-swap/canister-sdk", package = "ic-helpers", branch = "awkure/upgrade-fixes" }
ic-storage = { git = "https://github.com/infinity-swap/canister-sdk", package = "ic-storage", branch = "awkure/upgrade-fixes" }
ic-factory = { git = "https://github.com/infinity-swap/canister-sdk", package = "ic-factory", branch = "awkure/upgrade-fixes" }
serde = "1.0"
thiserror = "1.0"
token = { path = "../token/api", features = ["no_api"], package = "is20-token" }

[dev-dependencies]
tokio = { version = "1", features = ["rt", "macros"] }
